### PR TITLE
Initial redesign of analysis page

### LINKED ISSUE #5: Redesign Analysis Page
Redesign the Analysis report page.

### PR DESCRIPTION
**Pull request by jayeclark**
Signed-off-by: Jay Clark <jay@jayeclark.dev>

Fixes #5 

I've implemented v1 of the analysis page redesign. The figma docs show the ability to upload multiple PDFs and display multiple results on one page, which obviously hasn't been implemented in the app yet -- however, I've styled the 'file' section at the top of the page to accommodate this eventual functionality. (As a result, that section looks kind of needlessly overcomplicated at the moment, but that particular styling is helpful for the eventual conversion to multiple pdf's per page.)

I have to focus on some other projects, but if I could return in a bit for V2 I'd love to refactor the page to use Flask's parent-child block templating (ie separate out the PDF and URL lists into separate templates), as well as work on the quality & appearance of the downloaded report.

I *think* I could probably also tackle the switch to uploading multiple PDFs, but the response time of the script would probably have to be improved prior to taking that step. Either that or the analysis page would have to be significantly refactored so that it loads on completion of the first analysis, and the others load in dynamically as they are completed.

I've included screenshots below of the appearance at different viewport widths. 
Screen Shot 2021-12-15 at 4 44 14 PM
Screen Shot 2021-12-15 at 4 44 25 PM
Screen Shot 2021-12-15 at 4 44 38 PM
Screen Shot 2021-12-15 at 4 45 29 PM
Screen Shot 2021-12-15 at 4 45 46 PM

### CODE REVIEW

**Comment by marshalmiller** [comment]
Addressed Issue #6.

**Comment by marshalmiller** [comment]
@jayeclark You are truly a blessing to this project. Amazing work!

**Comment by marshalmiller** [comment]
@jayeclark I really do appreciate all that you have done. I'll work on the script response time in the meantime. Hopefully, I can implement that. I do have one design question. And please don't feel any obligation to do it. You've done so much already. Do you think we could make the Document Details section collapsable? I'd like to keep the section but it really does look like a mess now that you've made the rest of the page so nice.

**Comment by jayeclark** [comment]
@marshalmiller Sure, that's an easy enough add. I might play around with some of the formatting of the data in that section as well.

**Pull request merged**
